package com.santansarah.blescanner.presentation.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFff4800)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F6)
val md_theme_light_onPrimaryContainer = Color(0xFF380038)
val md_theme_light_secondary = Color(0xFF40e0d0)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB0ECFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F27)
val md_theme_light_tertiary = Color(0xFF8723D7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF1DBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF2D0050)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFAAAAAB)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)
val md_theme_light_inverseOnSurface = Color(0xFFECEFF0)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFFFAAF4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_outlineVariant = Color(0xFFD1C2CB)
val md_theme_light_scrim = Color(0xFF000000)

// cards
val md_theme_light_surface = Color(0xFFefefd1)
val md_theme_light_surfaceVariant = Color(0xFFefefd1)
val md_theme_light_surfaceTint = Color(0xFFefefd1)
val md_theme_light_onSurface = Color(0xFF0e100f)
val md_theme_light_outline = Color(0xFF5a6860)

val md_theme_dark_primary = Color(0xFFfff500)
val md_theme_dark_onPrimary = Color(0xFF0e100f)
val md_theme_dark_primaryContainer = Color(0xFF810082)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F6)
val md_theme_dark_secondary = Color(0xFF1CD8FF)
val md_theme_dark_onSecondary = Color(0xFF003641)
val md_theme_dark_secondaryContainer = Color(0xFF004E5E)
val md_theme_dark_onSecondaryContainer = Color(0xFFB0ECFF)
val md_theme_dark_tertiary = Color(0xFFDEB7FF)
val md_theme_dark_onTertiary = Color(0xFF4A007F)
val md_theme_dark_tertiaryContainer = Color(0xFF6A00B1)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1DBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFFA800AA)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)

val md_theme_dark_surface = Color(0xFF0e100f)
val md_theme_dark_surfaceVariant = Color(0xFF0e100f)
val md_theme_dark_onSurface = Color(0xFFc7c1bd)
val md_theme_dark_onSurfaceVariant = Color(0xFFc7c1bd)
val md_theme_dark_outline = Color(0xFFff8300)
val md_theme_dark_surfaceTint = Color(0xFFc7c1bd)


val seed = Color(0xFFFF33FF)
